# Generated by Django 2.1.5 on 2019-02-06 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.BinaryField()),
                ('is_dir', models.BooleanField()),
                ('meta', models.BinaryField(blank=True)),
                ('blocks', models.TextField(blank=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.Node')),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.Node')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Node')),
            ],
        ),
    ]
