# Generated by Django 2.1.5 on 2019-02-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='is_dir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.BinaryField(blank=True),
        ),
    ]
